spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?createDatabaseIfNotExist=true
    username: root
    password:
  flyway:
    schemas: cloud
    baseline-on-migrate: true
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
security:
  jwt:
    secret: ZmVzcnNyZ3dyZWR0ZGh0cmprZmRodHNoZmdoc2RnaEtIWUtZSE9MSEw=
    access: 1